package com.cah.eit.ea.app.standarddb.types;

public enum Level1Enum {
	BUSINESS_ARCHITECTURE,
	GOVERNANCE,
	APPLICATION_ARCHITECTURE,
	INFORMATION_ARCHITECTURE,
	TECHNICAL_ARCHITECTURE,
	SECURITY_ARCHITECTURE;
}
